name: Test project

on: push

jobs:
  testAllModes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./CITestUnity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
